### ISSUE TITLE
'raisely local' redirects to the live site

### ISSUE THREAD

**Issue by jw176** [raisely/cli#29]
Hi there,

I am trying to use the `raisely local` command so I can modify some code and test it locally before pushing it to our live site.
I have just noticed that whenever I run this command (or visit http://localhost:8015 directly) it will redirect to the domain where the live site is hosted, rather than staying on localhost.

This makes it harder to try and update code on the live site without affecting the users.
Please let me know if there is a workaround for this.

Cheers,
Jack

**Comment by tommaitland** [comment]
Hey Jack,

I'm guessing this is happening when you're working on a campaign that has a custom domain? At the moment there isn't a way for the CLI to handle that well, but we could probably update the proxy to follow redirects.

In the meantime, you could duplicate the campaign to a development version which doesn't have the custom domain enabled?

**Comment by jw176** [comment]
Hi Tom,

Thanks for the response. Yes, the issue occurs when using a custom domain. I have duplicated the campaign for testing, and it seems to be a suitable workaround. Cheers

**Comment by alexnitta** [comment]
Can we re-open this issue, in hopes of adding the feature of allowing the proxy to follow redirects? I would also like to use `raisely local` with a custom domain. I understand there is a workaround, but it would be really nice to have this functionality.
