### ISSUE TITLE
Add current campaign message to warning

### ISSUE THREAD

**Issue by agentlewis** [raisely/cli#31]
I am aware that custom components are deployed org wide, so this is less important for components.

However for deploying scss it would be good if the warning also told you which campaign you are overiting.

Obviously it matters less if you have disabled the ability for users to edit files through the ui, but as we are transitioning our client from ui edits to source controlled edits, thats not the case for us.

![image](https://user-images.githubusercontent.com/1431991/178338575-50b032ea-1546-4697-ace3-30533f2f8aff.png)

**Comment by tommaitland** [comment]
Currently `raisely deploy` deploys all of the campaigns in your `.raisely.json` file (see reply to https://github.com/raisely/cli/issues/34). We could still list them out here though, would happily accept a PR on this.

**Comment by agentlewis** [comment]
@tommaitland i followed the QuickStart guide and I don’t render it telling me to edit the campaigns in the .raisely.json file.

if I add the uuid for the staging and production environments, will this mean it deploys to both every time? 

Regarding the message, I think what throws me is that you can still deploy to a campaign even if the campaign array is empty in the .raisely.json file.

mid that is the config place I’d expect it yo error out of its empty.
