### ISSUE TITLE
Stylesheet files treated as Campaigns?

### ISSUE THREAD

**Issue by agentlewis** [raisely/cli#35]
This just seems really odd

![image](https://user-images.githubusercontent.com/1431991/178348122-4846267d-bb52-45a5-977d-3d0907275ce3.png)

**Comment by tommaitland** [comment]
Currently each campaign has a base file which is the file you see when you edit styles via the Raisely admin panel. Files in subfolders are only accessible via the CLI.

The CLI names that file as the campaign path. This was a pattern introduced before we allowed you to create subfolders/files in the campaign directory, and we used the filename to link the CSS file to the campaign.

As we now have a directory and the directory uses the campaign path we don't need to rely on the filename. This should be a fairly simply change to the `fetchStyles()` method [here](https://github.com/raisely/cli/blob/master/src/actions/campaigns.js#L27-L56) to simply detect a CSS file within the campaign directory.
