### ISSUE TITLE
"raisely local" not working

### ISSUE THREAD

**Issue by jw176** [raisely/cli#52]
I'm unable to get `raisely local` to work for the following reasons:
- The local dev server (http://localhost:8015/) redirects straight to the live site (which is not using a custom domain currently).
- The changes made to local scss file are not detected by the CLI (there is no change in terminal output similar to how `raisely start` behaves)

Any help with this issue would be appreciated. Thanks

**Comment by alexey-systemseed** [comment]
I have the same problem.

**Comment by pku2319** [comment]
Released 1.8.3 to address this issue
